const Command = require('../struct/Command');

let channels = {}

const text = [
    "DO NOT PRESS",
    "*Ahem*\nDO NOT PRESS",
    "... you pressed it again.\nOkay punk, press it again.",
    "Yeah, that's it.\nCome on, one more time.",
    "Again.",
    "Do it.",
    "Okay, now you've had your fill.\nStop clicking.",
    "You see, this is why\nwe can't be friends.",
    "You're just too selfish.",
    "Grr... now you've asked for it.\nDo NoT pReSs ThE bUtToN!",
    "You seem to be immune to\nmy mind control.",
    "Time for Plan B.\nPress it. You know you want to.",
    "Mwahahaha! Now let's see\nyou press it! LOSER!",
    "...this displeases me.",
    "HA! I have replaced the button\nwith this penguin. Now what are you\ngoing to do?",
    "...I hate you.",
    "In that \"cut off your head with a\ntoothbrush\" kind of way.",
    "Quick! What's that behind you?!",
    "Which one is it?\nNot so smart now, are ya?",
    "You're a clever one.\nTime for Round 2.",
    "HAHAHAHAHAHA!",
    "...",
    "Okay Okay. You can press the button.\nI don't care.",
    "No really, I don't care anymore.",
    "In fact, I lost interest a while ago.",
    "I'm doing this just to entertain you.",
    "Really.",
    "Do you like cartoons?",
    "...and paint?",
    "Cartoons and Paint?",
    "Well you should.",
    "Pick a colour.",
    "Green. Perfect.",
    "Press the red button.",
    "Press the green button",
    "Press the blue button",
    "See, you just can't trust me.\nOr can you?",
    "You know, I'm glad we get\nto spend so much time together.",
    "Doesn't it make you want to stop\nclicking big red buttons?",
    "No seriously.",
    "Look deep inside you.",
    "Deeper.",
    "DEEPER!",
    "What if I told you that that the next\ntime you press the button, the world\nwill explode?",
    "See. You could have been\ndead right there.",
    "And there.",
    "You know, eventually\nI'll stop letting you get away with this.",
    "The world is going to explode\nand all you care about is pressing buttons",
    "Okay, this time the world will\nexplode. I guarantee.",
    "BOOM!\nYou're dead.",
    "That wasn't very smart now was it?",
    "Everyone's dead. Even you.",
    "I'm not. I'm just text.",
    "But you're dead.",
    "Ha! Dead-face!",
    "Stop clicking.",
    "Have I ever told you how much I hate you?",
    "Well I do.",
    "I'm gonna start talking upside down\nif you click one more time.",
    "HA! Can't read me now, can you?",
    "What? You didn't want to read me anyway?",
    "Well then, i'll show you!",
    "You really are stubborn.",
    "Stop clicking. Please.",
    "See look. You've reduced me\nto begging. So please stop.",
    "PLEASE!!!!",
    "I'll give you a nickle",
    "Dime?",
    "Quarter?",
    "Aww come on! Just stop!",
    "That does it! Time to\nunleash my master plan!",
    "BEHOLD! \nThe awesome power of flash animation!",
    "H8!",
    "Let's get funky!",
    "I'll be you're starting to wonder\nwhy you've been doing this\nfor so long.",
    "Like jeez, all you've been doing is\nclicking a red button.",
    "How lame is that?",
    "But there is a bonus to all this",
    "But it's a secret.\nSo I can't tell you.",
    "I got you going didn't I?",
    "You should've seen the look\non your face! HA!",
    "But seriously, there is a secret.\nThere's been one the whole time.",
    "You've been busy clicking away at\nthis big red button...",
    "...when all the while a little white\nbutton as watched your every move",
    "MWAHAHAHAHAHA!",
    "HAHAHA!",
    "BWAHAA!",
    "MWAAAAH!!",
    "HAHA!",
    "hehe!",
    "lol",
    "rofl",
    "roflmao",
    "roflmaoqxz",
    "and so on and so forth",
    "*whistles*",
    "Find it yet?",
    "Look harder! \nIt's right under your nose.",
    "I know where it is.\nBut I'll never tell.",
    "Or maybe I will...",
    "But you gotta stop clicking the\nBig Red Button first!",
    "Stop.",
    "Now.",
    "Fine, I won't tell you\nthe secret.",
    "Go ahead. Try to find it yourself.\nYou'll never find it.",
    "Well you might... but the odds\nare against you.",
    "~",
    "What's your favorite letter?",
    "Mine is the squiggly!",
    "No?",
    "Then stop clicking and I'll tell you.",
    "You know what?",
    "POOF! It's gone!",
    "Has anyone ever slapped you?",
    "Cuz I will.",
    "Really I will.",
    "It won't hurt though.",
    "Cuz you're dead.",
    "D-E-D",
    "Remember? You went and blew up\nthe entire planet!",
    "Thought I'd forget about that\ndidn't you?",
    "But an elephant never forgets!",
    "...or something along those lines.",
    "You killed everyone.",
    "Sikko.",
    "What would you're mother say?",
    "That's right... feel bad.",
    "The world is null and you're to blame.",
    "I'd recommend suicide, \nbut you're dead already.",
    "So there's only one thing left\nthat you can do...",
    "Stop clicking the button.",
    "Dude, you're dead.\nWhat are you gaining from this?",
    "Okay, everytime you click, you\nget sent to a lower layer of hell.",
    "Welcome to layer 2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "BOOM!\nYou've exploded Hell.",
    "I hope you're happy.",
    "Heavens gone too.\nThat's how smooth you are.",
    "No you're dead, and there's\nno heaven or hell.",
    "How does it feel?\nYou've condemned the world to limbo.",
    "I once shot a man for being in limbo.",
    "...or was he doing the limbo?",
    "Meh, Tomato Tomahto",
    "This is getting boring isn't it?",
    "But you can't stop!",
    "You want to end this.\nYou want to leave you're computer.",
    "But you can't!",
    "You need to see if there's a pot of gold\nat the end of the rainbow!",
    "But I've already told you how to\nfind the pot of gold",
    "Follow the white rabbit.",
    "..erm, button.",
    "Remember the hidden button?",
    "Or are you so self-centered you\nforgot about that too?",
    "I could just keep you here all day\nif I wanted.",
    "You're in my world now.",
    "No matter how much you\nhate it, you have to press the button.",
    "again...",
    "and again...",
    "and again.",
    "You just keep hoping something\ngood will come of this.",
    "Sure I could tell you if I wanted\nto, but I'm not gonna.",
    "You decided to keep clicking.\nSo I'm gonna enjoy it.",
    "I mean, there's nothing else to enjoy",
    "You blew it all up remember?",
    "You're probably wondering who I am",
    "Well let me tell you a tale about myself",
    "One day, I was walking home from\nwork and I saw a small little house.",
    "I knocked on the door out of curiousity\nto see if anyone was home.",
    "The door opened.",
    "But no one was there.",
    "I went inside to check it out\nand found nothing...",
    "...nothing but a little metal box.",
    "So I opened it.",
    "Inside the box was a layer of\nfoam protecting it's contents",
    "I removed the foam and there it was...",
    "... ...",
    "ZZZzzzzzz",
    "zzzzZZZZzzzz",
    "ZZZZzzzZZZZ",
    "Huh?",
    "Oh! Right! The story!",
    "So there I was, holding this\nlittle metal box in my hands.",
    "The top was open and sitting\ninside was this...",
    "Big Red Button.",
    "And do you know what it said?",
    "Oh I'll tell you what it said.\nIt said..."
]

module.exports = new Command('pressthebutton')
    .setCategory('fun')
    .setUsage('Do not use this command')
    .alias(["ptb"])
    .inDm(false)
    .userPerms([])
    .botPerms([])
    .setArgs([])
    .setExec((message, bot) => {
        
        let id = message.channel.id

        if (!channels[id]) channels[id] = 0

        message.send(text[channels[id]])

        channels[id]++

        if (channels[id] > text.length-1) delete channels[id]

    })